24 fe add search component withwithout add post
filipgrabovac-fer/UNIZq pull request #33
Opened 2024-12-06 17:18 UTC by sucicAnamarija

Made search  component with/without add post div

2024-12-08 12:16 UTC, filipgrabovac-fer requested changes

2024-12-08 12:16 UTC, filipgrabovac-fer commented on IzvorniKod/frontend/src/components/CustomButton/CustomButton.tsx
> -          ? "bg-primary  text-white"
mozda bi da ovdje odredimo visinu buttona koji ce se koristit u cijelom projektu. Duljina moze varirat ali visina nek bude fiksna (npr 30px, mozes ih pretvorit u rem-ove). Isto tako imaj na umu da se CustomButton moze nac u raznim situacijama i da ovaj padding mozda nece odgovarat na nekom mobile viewu. Uvijek prvo dobro istestiraj sve

2024-12-08 12:16 UTC, filipgrabovac-fer commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +      <p>Date</p>
pazi na responzivnost, ovaj tekst treba smanjiti kad dodemo u mobile view

2024-12-08 12:16 UTC, filipgrabovac-fer commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +
ova funkcija nam ne treba, mozes odmah u onChange funkciji na inputu napisat ovako
`.... onChange={(event)=>setSearchContent(event.target.value)}`

2024-12-08 12:16 UTC, filipgrabovac-fer commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +        <MagnifyingGlassIcon className="h-6 text-black" />
previsok nam je input, smanji ga na 40px (mozes pretvorit sve piksele u rem-ove, imas na webu neku aplikaciju koja uzme piksele i pretvori u remove)

i mozda bi smanjio malo gap, postavi na 2 pa vidi kako ce izgledat

2024-12-08 12:16 UTC, filipgrabovac-fer commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +        <div className="h-[80%] border-l-[1px] border-black"></div>
problem sa ovim postocima u width-u je taj sto kada odes u mobile view ne radi bas najbolje (primjer u prilogu)

<img width="389" alt="Screenshot 2024-12-08 at 1 12 41 PM" src="https://github.com/user-attachments/assets/0a5349c8-dd47-4066-9b44-6de680030d5b">

malo se poigraj s time da nam na mobile viewu izgleda okej

2024-12-08 12:16 UTC, filipgrabovac-fer commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +        <div className="h-[80%] border-l-[1px] border-black"></div>
kao sto vidis ovdje onaj padding na buttonu igra veliku ulogu

2024-12-08 12:22 UTC, sucicAnamarija commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +
21e141ed6d913d1b573e8d3c7c59d74c7791fabd

2024-12-08 12:22 UTC, sucicAnamarija commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +
21e141ed6d913d1b573e8d3c7c59d74c7791fabd

2024-12-08 12:22 UTC, sucicAnamarija commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +
21e141ed6d913d1b573e8d3c7c59d74c7791fabd

2024-12-09 11:29 UTC, sucicAnamarija commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +
21e141ed6d913d1b573e8d3c7c59d74c7791fabd

2024-12-09 12:38 UTC, sucicAnamarija commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +        <MagnifyingGlassIcon className="h-6 text-black" />
a61ff16b5593aaf4313e93d676ddb07741467420

2024-12-09 12:54 UTC, sucicAnamarija commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +        <div className="h-[80%] border-l-[1px] border-black"></div>
5ae0a47d16f6b6291eaf857cb8ec39a71bc74fe1

2024-12-09 12:57 UTC, sucicAnamarija commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +
21e141ed6d913d1b573e8d3c7c59d74c7791fabd

2024-12-09 12:57 UTC, sucicAnamarija commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +        <div className="h-[80%] border-l-[1px] border-black"></div>
5ae0a47d16f6b6291eaf857cb8ec39a71bc74fe1

2024-12-09 12:57 UTC, sucicAnamarija commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +        <MagnifyingGlassIcon className="h-6 text-black" />
a61ff16b5593aaf4313e93d676ddb07741467420

2024-12-17 22:22 UTC, filipgrabovac-fer requested changes

2024-12-17 22:22 UTC, filipgrabovac-fer commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +          <Button className=" text-black rounded-[20px] h-full text-[18px] flex items-center gap-3 hover:border-none hover:text-black focus:outline-none">
bilo bi super kad bi cijeli ovaj popover zamijenili sa Select komponentom iz antd-a. Mislim da je jednostavnije upravljat s njom i da je generalno ljepsa (malo prouci)

2024-12-19 10:45 UTC, sucicAnamarija commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +          <Button className=" text-black rounded-[20px] h-full text-[18px] flex items-center gap-3 hover:border-none hover:text-black focus:outline-none">
93965a75e033038eaf7fe8e4757bf723f942a622

2025-01-04 09:03 UTC, sucicAnamarija commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +      <p>Date</p>
56bb91d6135897ffb284ba683b7e5529806ed877

2025-01-04 09:04 UTC, sucicAnamarija commented on IzvorniKod/frontend/src/components/Search/Search.tsx
> +      <p>Date</p>
56bb91d6135897ffb284ba683b7e5529806ed877

2025-01-04 09:14 UTC, sucicAnamarija commented
Kad stignes samo pogledaj ovo, cisto da neke stvari imam zavrseno :)
Lp, hvalaa

2025-01-08 08:48 UTC, merged