41 fe create sidebar nav
filipgrabovac-fer/UNIZq pull request #46
Opened 2024-12-21 15:14 UTC by sucicAnamarija

Napravila sam inicijalni dizaj, popravila Header i SidebarLayout tako da se pokazuje hambi menu kad smo na manjem ekranu i napravila sam da se automatski mijenja iz jednog prikaza u drugi (a ne da ceka refresh kako je to prije bilo). Kad se ovo pregleda, neka mi se javi pa da znam eventualno  popravit ako nesto ne valja.

2024-12-25 14:56 UTC, filipgrabovac-fer requested changes

2024-12-25 14:56 UTC, filipgrabovac-fer commented on IzvorniKod/frontend/src/components/Sidebar/Sidebar.tsx
> +    console.log("click ", e);
pls makni ovaj console.log

2024-12-25 14:56 UTC, filipgrabovac-fer commented on IzvorniKod/frontend/src/components/Sidebar/Sidebar.tsx
> +          }}
ovaj dio treba malo refaktorirati. Moramo imati 2 Menu tagga, jedan za fakultete jedan za evente u kojima mozemo rec da kad se klikne na faks i godinu (ako se radi o fakultetu i godinama na fakultetu) da se usera preusmjeri na link koji ce biti ovakav `faculty/{facultyId}/year/{facultyYearId}`, a ako se klikne na neki od evenata onda ga se preusmjerava na events page - `/events`- za ovo me pitaj da se cujemo pa da ti obj sta treba

2024-12-25 14:56 UTC, filipgrabovac-fer commented on IzvorniKod/frontend/src/layouts/SidebarLayout/SidebarLayout.tsx
> +  }, []);
ovaj dio nam ne treba, prikaz sidebara se moze handleati sa tailwindom i radilo je prije (pitaj me ako ti nije jasno)

2024-12-25 16:28 UTC, sucicAnamarija commented on IzvorniKod/frontend/src/components/Sidebar/Sidebar.tsx
> +    console.log("click ", e);
eb4dfe9dd4881ce3bd71f2dff675c02692d877ea

2025-01-04 09:13 UTC, sucicAnamarija commented
napravila sam na neki drugi nacin pa kad ces imat vremena pogledaj

2025-01-05 20:51 UTC, merged